### ISSUE TITLE
clash yaml 用通配符"＋"的写法的规则转化后丢失域名第一个字符

### ISSUE THREAD

**Issue by MrCloudyGod** [Toperlock/sing-box-geosite#2]
例如
payload:
  - '+.zcool.com.cn'
  - '+.zcool.cn'

转换后的json里会变成
{
  "rules": [
    {
      "domain": [
        "cool.cn",
        "cool.com.cn"
      ]
    },
    {
      "domain_suffix": [
        ".cool.cn",
        ".cool.com.cn"
      ]
    }
  ],
  "version": 1
}

测试了所有带通配符+号的规则转换后都有这个问题
想使用下面这个作者的clash规则
https://github.com/Loyalsoldier/clash-rules

**Comment by Toperlock** [comment]
奇怪，我怎么会写错。修了
