### ISSUE TITLE
你好，我尝试在生成的配置文件中加入你仓库里的wechat规则集，但似乎没有生效。

### ISSUE THREAD

**Issue by ksi1110** [Toperlock/sing-box-geosite#4]
开发者你好，我刚转入sing-box不久，之前一直在用v2ray，我尝试将正在使用的vless节点转换到sing-box的配置文件中，但每次打开后wechat都不能连接，搜索发现你写的wechat规则集，试着整合到配置文件中，但是依旧没有生效，请帮忙审查一下，是哪里出错。

·························
  {
      "tag": "📺 Bilibili",
      "type": "selector",
      "outbounds": [
        "direct"
      ]
    },
    {
      "tag": "🎉 WeChat",
      "type": "selector",
      "outbounds": [
        "direct"
      ]
    },
·······························

{
        "rule_set": "geosite-bilibili",
        "outbound": "📺 Bilibili"
      },
      {
        "rule_set": "geosite-wechat",
        "outbound": "🎉 WeChat"
      },
      {
        "rule_set": "geoip-netflix",
        "outbound": "🎬 MediaVideo"
      },
·······························
{
        "tag": "geosite-geolocation-!cn",
        "type": "remote",
        "format": "binary",
        "url": "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/geolocation-!cn.srs",
        "download_detour": "direct"
      },
      {
        "tag": "geosite-wechat",
        "type": "remote",
        "format": "source",
        "url": "https://raw.githubusercontent.com/Toperlock/sing-box-geosite/main/wechat.json",
        "download_detour": "auto"
      },
··········································

**Comment by Toperlock** [comment]
试试转换surge的wechat规则集
`https://raw.githubusercontent.com/Toperlock/sing-box-geosite/main/rule/WeChat.json`
